# Build phase: Create Docker image
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'
      - .

  # Push phase: Upload image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'

  # Deploy phase: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - $_REGION
      - '--platform'
      - managed
      - '--allow-unauthenticated'

# Add this options section
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: 'petwell-app'
  _REGION: 'us-central1'

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'
